// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9LW2kcugSPklt0tPk0X17jIE38b1t9JI',
    appId: '1:505366963170:web:381bd5b97a14558368cfbb',
    messagingSenderId: '505366963170',
    projectId: 'recipesapp-4cd7f',
    authDomain: 'recipesapp-4cd7f.firebaseapp.com',
    storageBucket: 'recipesapp-4cd7f.firebasestorage.app',
    measurementId: 'G-NJE4Y2KK2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUMgs58JWaqUMqT17mtNZVsd7MPP8uM2w',
    appId: '1:505366963170:android:26f275d12427776c68cfbb',
    messagingSenderId: '505366963170',
    projectId: 'recipesapp-4cd7f',
    storageBucket: 'recipesapp-4cd7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnD1VZ8c2C_7Dp5X-dOCf39w9kghX9YnM',
    appId: '1:505366963170:ios:5cdbbde0d706bd9168cfbb',
    messagingSenderId: '505366963170',
    projectId: 'recipesapp-4cd7f',
    storageBucket: 'recipesapp-4cd7f.firebasestorage.app',
    iosBundleId: 'com.example.myRecipesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnD1VZ8c2C_7Dp5X-dOCf39w9kghX9YnM',
    appId: '1:505366963170:ios:5cdbbde0d706bd9168cfbb',
    messagingSenderId: '505366963170',
    projectId: 'recipesapp-4cd7f',
    storageBucket: 'recipesapp-4cd7f.firebasestorage.app',
    iosBundleId: 'com.example.myRecipesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9LW2kcugSPklt0tPk0X17jIE38b1t9JI',
    appId: '1:505366963170:web:219dcc0e8b5e362468cfbb',
    messagingSenderId: '505366963170',
    projectId: 'recipesapp-4cd7f',
    authDomain: 'recipesapp-4cd7f.firebaseapp.com',
    storageBucket: 'recipesapp-4cd7f.firebasestorage.app',
    measurementId: 'G-NCMZ1Q3JDK',
  );
}
